import type { DocumentTheme } from "@/types/style"

export const THEME_DEFINITIONS: Record<string, DocumentTheme> = {
  "editorial-serif": {
    name: "editorial-serif",
    displayName: "Editorial Serif",
    fonts: {
      body: {
        family: "Lora",
        size: 16,
        lineHeight: 1.85,
        letterSpacing: 0.01,
        weight: 400,
      },
      heading: {
        family: "Playfair Display",
        size: 34,
        lineHeight: 1.25,
        letterSpacing: -0.02,
        weight: 700,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 13,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 38,
        fontWeight: 800,
        color: "#1a1209",
        spacingTop: 16,
        spacingBottom: 16,
        borderBottom: true,
        underline: false,
      },
      h2: {
        fontSize: 30,
        fontWeight: 700,
        color: "#2c1f0e",
        spacingTop: 40,
        spacingBottom: 12,
        borderBottom: false,
        underline: false,
      },
      h3: {
        fontSize: 22,
        fontWeight: 600,
        color: "#c8622a",
        spacingTop: 32,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 18,
        fontWeight: 600,
        color: "#c8622a",
        spacingTop: 24,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 16,
        fontWeight: 600,
        color: "#a0522d",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 600,
        color: "#a0522d",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#1a1209",
        h2: "#2c1f0e",
        h3: "#c8622a",
        h4: "#c8622a",
        h5: "#a0522d",
        h6: "#a0522d",
      },
      bodyTextColor: "#2c1f0e",
      secondaryTextColor: "#8a7d6b",
      linkColor: "#c8622a",
      visitedLinkColor: "#a0522d",
      blockquoteBorderColor: "#c8622a",
      blockquoteBackgroundColor: "#fdf6ee",
      tableHeaderBackground: "#2c1f0e",
      tableHeaderTextColor: "#faf7f2",
      tableRowAlternateColor: "#f5f0e8",
      tableBorderColor: "#dcd3c8",
      inlineCodeBackground: "#f2ede5",
      inlineCodeTextColor: "#c8622a",
      pageBackgroundColor: "#faf7f2",
    },
    bodyText: {
      paragraphSpacing: 18,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "github-light",
  },

  "clean-slate": {
    name: "clean-slate",
    displayName: "Clean Slate",
    fonts: {
      body: {
        family: "DM Sans",
        size: 15,
        lineHeight: 1.75,
        letterSpacing: -0.01,
        weight: 400,
      },
      heading: {
        family: "DM Sans",
        size: 32,
        lineHeight: 1.2,
        letterSpacing: -0.03,
        weight: 800,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 13,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 900,
        color: "#0f172a",
        spacingTop: 16,
        spacingBottom: 14,
        borderBottom: false,
        underline: false,
      },
      h2: {
        fontSize: 26,
        fontWeight: 800,
        color: "#0f172a",
        spacingTop: 40,
        spacingBottom: 10,
        borderBottom: true,
        underline: false,
      },
      h3: {
        fontSize: 20,
        fontWeight: 700,
        color: "#1e40af",
        spacingTop: 28,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 17,
        fontWeight: 700,
        color: "#1e40af",
        spacingTop: 24,
        spacingBottom: 6,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 15,
        fontWeight: 600,
        color: "#2563eb",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 13,
        fontWeight: 600,
        color: "#3b82f6",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#0f172a",
        h2: "#0f172a",
        h3: "#1e40af",
        h4: "#1e40af",
        h5: "#2563eb",
        h6: "#3b82f6",
      },
      bodyTextColor: "#1e293b",
      secondaryTextColor: "#64748b",
      linkColor: "#2563eb",
      visitedLinkColor: "#1e40af",
      blockquoteBorderColor: "#3b82f6",
      blockquoteBackgroundColor: "#eff6ff",
      tableHeaderBackground: "#0f172a",
      tableHeaderTextColor: "#f8fafc",
      tableRowAlternateColor: "#f8fafc",
      tableBorderColor: "#e2e8f0",
      inlineCodeBackground: "#eff6ff",
      inlineCodeTextColor: "#1e40af",
      pageBackgroundColor: "#ffffff",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "github-light",
  },

  "forest-notebook": {
    name: "forest-notebook",
    displayName: "Forest Notebook",
    fonts: {
      body: {
        family: "Merriweather",
        size: 15,
        lineHeight: 1.9,
        letterSpacing: 0.01,
        weight: 400,
      },
      heading: {
        family: "Nunito",
        size: 32,
        lineHeight: 1.3,
        letterSpacing: -0.01,
        weight: 800,
      },
      monospace: {
        family: "Fira Code",
        size: 13,
        lineHeight: 1.65,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 800,
        color: "#14532d",
        spacingTop: 16,
        spacingBottom: 16,
        borderBottom: true,
        underline: false,
      },
      h2: {
        fontSize: 28,
        fontWeight: 700,
        color: "#166534",
        spacingTop: 40,
        spacingBottom: 12,
        borderBottom: false,
        underline: false,
      },
      h3: {
        fontSize: 22,
        fontWeight: 600,
        color: "#15803d",
        spacingTop: 32,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 18,
        fontWeight: 600,
        color: "#16a34a",
        spacingTop: 24,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 16,
        fontWeight: 600,
        color: "#22c55e",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 500,
        color: "#4ade80",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#14532d",
        h2: "#166534",
        h3: "#15803d",
        h4: "#16a34a",
        h5: "#22c55e",
        h6: "#4ade80",
      },
      bodyTextColor: "#1c2b1e",
      secondaryTextColor: "#4b6b52",
      linkColor: "#16a34a",
      visitedLinkColor: "#14532d",
      blockquoteBorderColor: "#22c55e",
      blockquoteBackgroundColor: "#f0fdf4",
      tableHeaderBackground: "#14532d",
      tableHeaderTextColor: "#f0fdf4",
      tableRowAlternateColor: "#f0fdf4",
      tableBorderColor: "#dcfce7",
      inlineCodeBackground: "#dcfce7",
      inlineCodeTextColor: "#15803d",
      pageBackgroundColor: "#f8fdf9",
    },
    bodyText: {
      paragraphSpacing: 18,
      textAlignment: "left",
      firstLineIndent: true,
    },
    codeTheme: "vitesse-light",
  },

  "rose-gold": {
    name: "rose-gold",
    displayName: "Rose Gold",
    fonts: {
      body: {
        family: "Nunito",
        size: 15,
        lineHeight: 1.8,
        letterSpacing: 0,
        weight: 400,
      },
      heading: {
        family: "Cormorant Garamond",
        size: 36,
        lineHeight: 1.2,
        letterSpacing: -0.01,
        weight: 700,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 13,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 40,
        fontWeight: 700,
        color: "#881337",
        spacingTop: 16,
        spacingBottom: 16,
        borderBottom: true,
        underline: false,
      },
      h2: {
        fontSize: 30,
        fontWeight: 700,
        color: "#9f1239",
        spacingTop: 40,
        spacingBottom: 12,
        borderBottom: false,
        underline: false,
      },
      h3: {
        fontSize: 22,
        fontWeight: 600,
        color: "#be123c",
        spacingTop: 32,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 18,
        fontWeight: 600,
        color: "#e11d48",
        spacingTop: 24,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 16,
        fontWeight: 600,
        color: "#f43f5e",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 500,
        color: "#fb7185",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#881337",
        h2: "#9f1239",
        h3: "#be123c",
        h4: "#e11d48",
        h5: "#f43f5e",
        h6: "#fb7185",
      },
      bodyTextColor: "#1f0a10",
      secondaryTextColor: "#9f7a84",
      linkColor: "#e11d48",
      visitedLinkColor: "#9f1239",
      blockquoteBorderColor: "#f43f5e",
      blockquoteBackgroundColor: "#fff1f2",
      tableHeaderBackground: "#881337",
      tableHeaderTextColor: "#fff1f2",
      tableRowAlternateColor: "#fff1f2",
      tableBorderColor: "#fee2e2",
      inlineCodeBackground: "#ffe4e6",
      inlineCodeTextColor: "#be123c",
      pageBackgroundColor: "#fffbfc",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "rose-pine",
  },

  // ─── DARK THEMES ────────────────────────────────────────────

  "midnight-ink": {
    name: "midnight-ink",
    displayName: "Midnight Ink",
    fonts: {
      body: {
        family: "Inter",
        size: 15,
        lineHeight: 1.8,
        letterSpacing: -0.01,
        weight: 400,
      },
      heading: {
        family: "Inter",
        size: 34,
        lineHeight: 1.2,
        letterSpacing: -0.03,
        weight: 800,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 13,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 800,
        color: "#e2e8f0",
        spacingTop: 16,
        spacingBottom: 16,
        borderBottom: true,
        underline: false,
      },
      h2: {
        fontSize: 28,
        fontWeight: 700,
        color: "#cbd5e1",
        spacingTop: 40,
        spacingBottom: 12,
        borderBottom: false,
        underline: false,
      },
      h3: {
        fontSize: 22,
        fontWeight: 600,
        color: "#38bdf8",
        spacingTop: 32,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 18,
        fontWeight: 600,
        color: "#38bdf8",
        spacingTop: 24,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 16,
        fontWeight: 600,
        color: "#7dd3fc",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 500,
        color: "#bae6fd",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#e2e8f0",
        h2: "#cbd5e1",
        h3: "#38bdf8",
        h4: "#38bdf8",
        h5: "#7dd3fc",
        h6: "#bae6fd",
      },
      bodyTextColor: "#cbd5e1",
      secondaryTextColor: "#64748b",
      linkColor: "#38bdf8",
      visitedLinkColor: "#7dd3fc",
      blockquoteBorderColor: "#0ea5e9",
      blockquoteBackgroundColor: "#0c1a2e",
      tableHeaderBackground: "#0f172a",
      tableHeaderTextColor: "#e2e8f0",
      tableRowAlternateColor: "#0f172a",
      tableBorderColor: "#1e293b",
      inlineCodeBackground: "#0c1a2e",
      inlineCodeTextColor: "#38bdf8",
      pageBackgroundColor: "#0d1117",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "github-dark",
  },

  "catppuccin-mocha": {
    name: "catppuccin-mocha",
    displayName: "Catppuccin Mocha",
    fonts: {
      body: {
        family: "DM Sans",
        size: 15,
        lineHeight: 1.8,
        letterSpacing: -0.01,
        weight: 400,
      },
      heading: {
        family: "DM Sans",
        size: 34,
        lineHeight: 1.2,
        letterSpacing: -0.02,
        weight: 700,
      },
      monospace: {
        family: "Fira Code",
        size: 13,
        lineHeight: 1.65,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 700,
        color: "#cba6f7",
        spacingTop: 16,
        spacingBottom: 16,
        borderBottom: true,
        underline: false,
      },
      h2: {
        fontSize: 28,
        fontWeight: 700,
        color: "#b4befe",
        spacingTop: 40,
        spacingBottom: 12,
        borderBottom: false,
        underline: false,
      },
      h3: {
        fontSize: 22,
        fontWeight: 600,
        color: "#89b4fa",
        spacingTop: 32,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 18,
        fontWeight: 600,
        color: "#89dceb",
        spacingTop: 24,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 16,
        fontWeight: 600,
        color: "#94e2d5",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 500,
        color: "#a6e3a1",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#cba6f7",
        h2: "#b4befe",
        h3: "#89b4fa",
        h4: "#89dceb",
        h5: "#94e2d5",
        h6: "#a6e3a1",
      },
      bodyTextColor: "#cdd6f4",
      secondaryTextColor: "#6c7086",
      linkColor: "#89b4fa",
      visitedLinkColor: "#b4befe",
      blockquoteBorderColor: "#cba6f7",
      blockquoteBackgroundColor: "#181825",
      tableHeaderBackground: "#1e1e2e",
      tableHeaderTextColor: "#cdd6f4",
      tableRowAlternateColor: "#181825",
      tableBorderColor: "#313244",
      inlineCodeBackground: "#181825",
      inlineCodeTextColor: "#cba6f7",
      pageBackgroundColor: "#1e1e2e",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "catppuccin-mocha",
  },

  "obsidian-amber": {
    name: "obsidian-amber",
    displayName: "Obsidian Amber",
    fonts: {
      body: {
        family: "Lora",
        size: 15,
        lineHeight: 1.85,
        letterSpacing: 0.01,
        weight: 400,
      },
      heading: {
        family: "Playfair Display",
        size: 34,
        lineHeight: 1.25,
        letterSpacing: -0.02,
        weight: 700,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 13,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 38,
        fontWeight: 800,
        color: "#fbbf24",
        spacingTop: 16,
        spacingBottom: 16,
        borderBottom: true,
        underline: false,
      },
      h2: {
        fontSize: 30,
        fontWeight: 700,
        color: "#f59e0b",
        spacingTop: 40,
        spacingBottom: 12,
        borderBottom: false,
        underline: false,
      },
      h3: {
        fontSize: 22,
        fontWeight: 600,
        color: "#d97706",
        spacingTop: 32,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 18,
        fontWeight: 600,
        color: "#b45309",
        spacingTop: 24,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 16,
        fontWeight: 600,
        color: "#fbbf24",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 500,
        color: "#fcd34d",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#fbbf24",
        h2: "#f59e0b",
        h3: "#d97706",
        h4: "#b45309",
        h5: "#fbbf24",
        h6: "#fcd34d",
      },
      bodyTextColor: "#d4c5a0",
      secondaryTextColor: "#78716c",
      linkColor: "#f59e0b",
      visitedLinkColor: "#d97706",
      blockquoteBorderColor: "#f59e0b",
      blockquoteBackgroundColor: "#1c1611",
      tableHeaderBackground: "#1c1611",
      tableHeaderTextColor: "#fbbf24",
      tableRowAlternateColor: "#1a1410",
      tableBorderColor: "#2a241e",
      inlineCodeBackground: "#1c1611",
      inlineCodeTextColor: "#fbbf24",
      pageBackgroundColor: "#141210",
    },
    bodyText: {
      paragraphSpacing: 18,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "dracula",
  },

  "nord-aurora": {
    name: "nord-aurora",
    displayName: "Nord Aurora",
    fonts: {
      body: {
        family: "Inter",
        size: 15,
        lineHeight: 1.8,
        letterSpacing: -0.01,
        weight: 400,
      },
      heading: {
        family: "Nunito",
        size: 34,
        lineHeight: 1.2,
        letterSpacing: -0.02,
        weight: 800,
      },
      monospace: {
        family: "Fira Code",
        size: 13,
        lineHeight: 1.65,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 800,
        color: "#88c0d0",
        spacingTop: 16,
        spacingBottom: 16,
        borderBottom: true,
        underline: false,
      },
      h2: {
        fontSize: 28,
        fontWeight: 700,
        color: "#81a1c1",
        spacingTop: 40,
        spacingBottom: 12,
        borderBottom: false,
        underline: false,
      },
      h3: {
        fontSize: 22,
        fontWeight: 600,
        color: "#5e81ac",
        spacingTop: 32,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 18,
        fontWeight: 600,
        color: "#a3be8c",
        spacingTop: 24,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 16,
        fontWeight: 600,
        color: "#ebcb8b",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 500,
        color: "#b48ead",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#88c0d0",
        h2: "#81a1c1",
        h3: "#5e81ac",
        h4: "#a3be8c",
        h5: "#ebcb8b",
        h6: "#b48ead",
      },
      bodyTextColor: "#d8dee9",
      secondaryTextColor: "#4c566a",
      linkColor: "#88c0d0",
      visitedLinkColor: "#81a1c1",
      blockquoteBorderColor: "#88c0d0",
      blockquoteBackgroundColor: "#2e3440",
      tableHeaderBackground: "#2e3440",
      tableHeaderTextColor: "#eceff4",
      tableRowAlternateColor: "#2e3440",
      tableBorderColor: "#3b4252",
      inlineCodeBackground: "#2e3440",
      inlineCodeTextColor: "#88c0d0",
      pageBackgroundColor: "#242933",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "nord",
  },
}
