import type { DocumentTheme } from "@/types/style"

export const THEME_DEFINITIONS: Record<string, DocumentTheme> = {
  "modern-purple": {
    name: "modern-purple",
    displayName: "Modern Purple",
    fonts: {
      body: {
        family: "Inter",
        size: 16,
        lineHeight: 1.75,
        letterSpacing: -0.01,
        weight: 400,
      },
      heading: {
        family: "Inter",
        size: 32,
        lineHeight: 1.3,
        letterSpacing: -0.02,
        weight: 700,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 14,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 800,
        color: "#6d28d9",
        spacingTop: 16,
        spacingBottom: 16,
        borderBottom: true,
        underline: false,
      },
      h2: {
        fontSize: 28,
        fontWeight: 700,
        color: "#7c3aed",
        spacingTop: 40,
        spacingBottom: 12,
        borderBottom: false,
        underline: false,
      },
      h3: {
        fontSize: 22,
        fontWeight: 600,
        color: "#8b5cf6",
        spacingTop: 32,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 18,
        fontWeight: 600,
        color: "#8b5cf6",
        spacingTop: 24,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 16,
        fontWeight: 600,
        color: "#a78bfa",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 600,
        color: "#a78bfa",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#6d28d9",
        h2: "#7c3aed",
        h3: "#8b5cf6",
        h4: "#8b5cf6",
        h5: "#a78bfa",
        h6: "#a78bfa",
      },
      bodyTextColor: "#1e293b",
      secondaryTextColor: "#64748b",
      linkColor: "#7c3aed",
      visitedLinkColor: "#6d28d9",
      blockquoteBorderColor: "#8b5cf6",
      blockquoteBackgroundColor: "#f5f3ff",
      tableHeaderBackground: "#6d28d9",
      tableHeaderTextColor: "#ffffff",
      tableRowAlternateColor: "#faf5ff",
      inlineCodeBackground: "#f5f3ff",
      inlineCodeTextColor: "#6d28d9",
      pageBackgroundColor: "#ffffff",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "catppuccin-mocha",
  },

  "ocean-blue": {
    name: "ocean-blue",
    displayName: "Ocean Blue",
    fonts: {
      body: {
        family: "Source Sans 3",
        size: 16,
        lineHeight: 1.75,
        letterSpacing: 0,
        weight: 400,
      },
      heading: {
        family: "Source Sans 3",
        size: 32,
        lineHeight: 1.3,
        letterSpacing: -0.02,
        weight: 700,
      },
      monospace: {
        family: "Fira Code",
        size: 14,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 800,
        color: "#1e3a5f",
        spacingTop: 16,
        spacingBottom: 16,
        borderBottom: true,
        underline: false,
      },
      h2: {
        fontSize: 28,
        fontWeight: 700,
        color: "#1e40af",
        spacingTop: 40,
        spacingBottom: 12,
        borderBottom: false,
        underline: false,
      },
      h3: {
        fontSize: 22,
        fontWeight: 600,
        color: "#2563eb",
        spacingTop: 32,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 18,
        fontWeight: 600,
        color: "#2563eb",
        spacingTop: 24,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 16,
        fontWeight: 600,
        color: "#3b82f6",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 600,
        color: "#3b82f6",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#1e3a5f",
        h2: "#1e40af",
        h3: "#2563eb",
        h4: "#2563eb",
        h5: "#3b82f6",
        h6: "#3b82f6",
      },
      bodyTextColor: "#0f172a",
      secondaryTextColor: "#475569",
      linkColor: "#2563eb",
      visitedLinkColor: "#1e40af",
      blockquoteBorderColor: "#3b82f6",
      blockquoteBackgroundColor: "#eff6ff",
      tableHeaderBackground: "#1e3a5f",
      tableHeaderTextColor: "#ffffff",
      tableRowAlternateColor: "#f0f9ff",
      inlineCodeBackground: "#eff6ff",
      inlineCodeTextColor: "#1e40af",
      pageBackgroundColor: "#ffffff",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "github-dark",
  },

  "forest-green": {
    name: "forest-green",
    displayName: "Forest Green",
    fonts: {
      body: {
        family: "Lora",
        size: 16,
        lineHeight: 1.8,
        letterSpacing: 0,
        weight: 400,
      },
      heading: {
        family: "Lora",
        size: 32,
        lineHeight: 1.3,
        letterSpacing: -0.01,
        weight: 700,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 14,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 800,
        color: "#065f46",
        spacingTop: 16,
        spacingBottom: 16,
        borderBottom: true,
        underline: false,
      },
      h2: {
        fontSize: 28,
        fontWeight: 700,
        color: "#047857",
        spacingTop: 40,
        spacingBottom: 12,
        borderBottom: false,
        underline: false,
      },
      h3: {
        fontSize: 22,
        fontWeight: 600,
        color: "#059669",
        spacingTop: 32,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 18,
        fontWeight: 600,
        color: "#059669",
        spacingTop: 24,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 16,
        fontWeight: 600,
        color: "#10b981",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 600,
        color: "#10b981",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#065f46",
        h2: "#047857",
        h3: "#059669",
        h4: "#059669",
        h5: "#10b981",
        h6: "#10b981",
      },
      bodyTextColor: "#1a2e1a",
      secondaryTextColor: "#4b6043",
      linkColor: "#047857",
      visitedLinkColor: "#065f46",
      blockquoteBorderColor: "#059669",
      blockquoteBackgroundColor: "#ecfdf5",
      tableHeaderBackground: "#065f46",
      tableHeaderTextColor: "#ffffff",
      tableRowAlternateColor: "#f0fdf4",
      inlineCodeBackground: "#ecfdf5",
      inlineCodeTextColor: "#065f46",
      pageBackgroundColor: "#ffffff",
    },
    bodyText: {
      paragraphSpacing: 18,
      textAlignment: "justify",
      firstLineIndent: false,
    },
    codeTheme: "nord",
  },

  "warm-amber": {
    name: "warm-amber",
    displayName: "Warm Amber",
    fonts: {
      body: {
        family: "Merriweather",
        size: 16,
        lineHeight: 1.8,
        letterSpacing: 0,
        weight: 400,
      },
      heading: {
        family: "Merriweather",
        size: 32,
        lineHeight: 1.3,
        letterSpacing: -0.01,
        weight: 700,
      },
      monospace: {
        family: "Fira Code",
        size: 14,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 800,
        color: "#92400e",
        spacingTop: 16,
        spacingBottom: 16,
        borderBottom: true,
        underline: false,
      },
      h2: {
        fontSize: 28,
        fontWeight: 700,
        color: "#b45309",
        spacingTop: 40,
        spacingBottom: 12,
        borderBottom: false,
        underline: false,
      },
      h3: {
        fontSize: 22,
        fontWeight: 600,
        color: "#d97706",
        spacingTop: 32,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 18,
        fontWeight: 600,
        color: "#d97706",
        spacingTop: 24,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 16,
        fontWeight: 600,
        color: "#f59e0b",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 600,
        color: "#f59e0b",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#92400e",
        h2: "#b45309",
        h3: "#d97706",
        h4: "#d97706",
        h5: "#f59e0b",
        h6: "#f59e0b",
      },
      bodyTextColor: "#292524",
      secondaryTextColor: "#78716c",
      linkColor: "#b45309",
      visitedLinkColor: "#92400e",
      blockquoteBorderColor: "#d97706",
      blockquoteBackgroundColor: "#fffbeb",
      tableHeaderBackground: "#92400e",
      tableHeaderTextColor: "#ffffff",
      tableRowAlternateColor: "#fefce8",
      inlineCodeBackground: "#fffbeb",
      inlineCodeTextColor: "#92400e",
      pageBackgroundColor: "#fffdf7",
    },
    bodyText: {
      paragraphSpacing: 18,
      textAlignment: "justify",
      firstLineIndent: true,
    },
    codeTheme: "monokai",
  },

  "minimal-gray": {
    name: "minimal-gray",
    displayName: "Minimal Gray",
    fonts: {
      body: {
        family: "Inter",
        size: 16,
        lineHeight: 1.7,
        letterSpacing: 0,
        weight: 400,
      },
      heading: {
        family: "Inter",
        size: 32,
        lineHeight: 1.3,
        letterSpacing: -0.02,
        weight: 600,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 14,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 700,
        color: "#18181b",
        spacingTop: 16,
        spacingBottom: 16,
        borderBottom: false,
        underline: false,
      },
      h2: {
        fontSize: 28,
        fontWeight: 600,
        color: "#27272a",
        spacingTop: 40,
        spacingBottom: 12,
        borderBottom: false,
        underline: false,
      },
      h3: {
        fontSize: 22,
        fontWeight: 600,
        color: "#3f3f46",
        spacingTop: 32,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 18,
        fontWeight: 600,
        color: "#3f3f46",
        spacingTop: 24,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 16,
        fontWeight: 600,
        color: "#52525b",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 600,
        color: "#52525b",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#18181b",
        h2: "#27272a",
        h3: "#3f3f46",
        h4: "#3f3f46",
        h5: "#52525b",
        h6: "#52525b",
      },
      bodyTextColor: "#27272a",
      secondaryTextColor: "#71717a",
      linkColor: "#3f3f46",
      visitedLinkColor: "#52525b",
      blockquoteBorderColor: "#a1a1aa",
      blockquoteBackgroundColor: "#fafafa",
      tableHeaderBackground: "#27272a",
      tableHeaderTextColor: "#ffffff",
      tableRowAlternateColor: "#f4f4f5",
      inlineCodeBackground: "#f4f4f5",
      inlineCodeTextColor: "#27272a",
      pageBackgroundColor: "#ffffff",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "github-light",
  },

  corporate: {
    name: "corporate",
    displayName: "Corporate",
    fonts: {
      body: {
        family: "Roboto",
        size: 16,
        lineHeight: 1.7,
        letterSpacing: 0,
        weight: 400,
      },
      heading: {
        family: "Roboto",
        size: 32,
        lineHeight: 1.3,
        letterSpacing: -0.01,
        weight: 700,
      },
      monospace: {
        family: "Roboto Mono",
        size: 14,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 800,
        color: "#0f172a",
        spacingTop: 16,
        spacingBottom: 16,
        borderBottom: true,
        underline: false,
      },
      h2: {
        fontSize: 28,
        fontWeight: 700,
        color: "#1e293b",
        spacingTop: 40,
        spacingBottom: 12,
        borderBottom: true,
        underline: false,
      },
      h3: {
        fontSize: 22,
        fontWeight: 600,
        color: "#334155",
        spacingTop: 32,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 18,
        fontWeight: 600,
        color: "#334155",
        spacingTop: 24,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 16,
        fontWeight: 600,
        color: "#475569",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 600,
        color: "#475569",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#0f172a",
        h2: "#1e293b",
        h3: "#334155",
        h4: "#334155",
        h5: "#475569",
        h6: "#475569",
      },
      bodyTextColor: "#1e293b",
      secondaryTextColor: "#64748b",
      linkColor: "#1e40af",
      visitedLinkColor: "#1e3a8a",
      blockquoteBorderColor: "#cbd5e1",
      blockquoteBackgroundColor: "#f8fafc",
      tableHeaderBackground: "#0f172a",
      tableHeaderTextColor: "#ffffff",
      tableRowAlternateColor: "#f1f5f9",
      inlineCodeBackground: "#f1f5f9",
      inlineCodeTextColor: "#334155",
      pageBackgroundColor: "#ffffff",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "vitesse-light",
  },
}
