import type { DocumentTheme } from "@/types/style"

export const THEME_DEFINITIONS: Record<string, DocumentTheme> = {
  "editorial-serif": {
    name: "editorial-serif",
    displayName: "Editorial Serif",
    fonts: {
      body: {
        family: "Lora",
        size: 15,
        lineHeight: 1.75,
        letterSpacing: -0.01,
        weight: 400,
      },
      heading: {
        family: "Playfair Display",
        size: 32,
        lineHeight: 1.2,
        letterSpacing: -0.03,
        weight: 700,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 13,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 800,
        color: "#1a1209",
        spacingTop: 16,
        spacingBottom: 14,
        borderBottom: false,
        underline: false,
      },
      h2: {
        fontSize: 26,
        fontWeight: 700,
        color: "#2c1f0e",
        spacingTop: 40,
        spacingBottom: 10,
        borderBottom: true,
        underline: false,
      },
      h3: {
        fontSize: 20,
        fontWeight: 600,
        color: "#c8622a",
        spacingTop: 28,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 17,
        fontWeight: 600,
        color: "#c8622a",
        spacingTop: 24,
        spacingBottom: 6,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 15,
        fontWeight: 600,
        color: "#a0522d",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 13,
        fontWeight: 600,
        color: "#a0522d",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#1a1209",
        h2: "#2c1f0e",
        h3: "#c8622a",
        h4: "#c8622a",
        h5: "#a0522d",
        h6: "#a0522d",
      },
      bodyTextColor: "#2c1f0e",
      secondaryTextColor: "#8a7d6b",
      linkColor: "#c8622a",
      visitedLinkColor: "#a0522d",
      blockquoteBorderColor: "#c8622a",
      blockquoteBackgroundColor: "#fdf6ee",
      tableHeaderBackground: "#2c1f0e",
      tableHeaderTextColor: "#faf7f2",
      tableRowAlternateColor: "#f5f0e8",
      tableBorderColor: "#dcd3c8",
      inlineCodeBackground: "#f2ede5",
      inlineCodeTextColor: "#c8622a",
      pageBackgroundColor: "#faf7f2",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "github-light",
  },

  "clean-slate": {
    name: "clean-slate",
    displayName: "Clean Slate",
    fonts: {
      body: {
        family: "DM Sans",
        size: 15,
        lineHeight: 1.75,
        letterSpacing: -0.01,
        weight: 400,
      },
      heading: {
        family: "DM Sans",
        size: 32,
        lineHeight: 1.2,
        letterSpacing: -0.03,
        weight: 800,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 13,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 900,
        color: "#0f172a",
        spacingTop: 16,
        spacingBottom: 14,
        borderBottom: false,
        underline: false,
      },
      h2: {
        fontSize: 26,
        fontWeight: 800,
        color: "#0f172a",
        spacingTop: 40,
        spacingBottom: 10,
        borderBottom: true,
        underline: false,
      },
      h3: {
        fontSize: 20,
        fontWeight: 700,
        color: "#1e40af",
        spacingTop: 28,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 17,
        fontWeight: 700,
        color: "#1e40af",
        spacingTop: 24,
        spacingBottom: 6,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 15,
        fontWeight: 600,
        color: "#2563eb",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 13,
        fontWeight: 600,
        color: "#3b82f6",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#0f172a",
        h2: "#0f172a",
        h3: "#1e40af",
        h4: "#1e40af",
        h5: "#2563eb",
        h6: "#3b82f6",
      },
      bodyTextColor: "#1e293b",
      secondaryTextColor: "#64748b",
      linkColor: "#2563eb",
      visitedLinkColor: "#1e40af",
      blockquoteBorderColor: "#3b82f6",
      blockquoteBackgroundColor: "#eff6ff",
      tableHeaderBackground: "#0f172a",
      tableHeaderTextColor: "#f8fafc",
      tableRowAlternateColor: "#f8fafc",
      tableBorderColor: "#e2e8f0",
      inlineCodeBackground: "#eff6ff",
      inlineCodeTextColor: "#1e40af",
      pageBackgroundColor: "#ffffff",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "github-light",
  },

  "forest-notebook": {
    name: "forest-notebook",
    displayName: "Forest Notebook",
    fonts: {
      body: {
        family: "Merriweather",
        size: 15,
        lineHeight: 1.75,
        letterSpacing: -0.01,
        weight: 400,
      },
      heading: {
        family: "Nunito",
        size: 32,
        lineHeight: 1.2,
        letterSpacing: -0.03,
        weight: 800,
      },
      monospace: {
        family: "Fira Code",
        size: 13,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 800,
        color: "#14532d",
        spacingTop: 16,
        spacingBottom: 14,
        borderBottom: false,
        underline: false,
      },
      h2: {
        fontSize: 26,
        fontWeight: 700,
        color: "#166534",
        spacingTop: 40,
        spacingBottom: 10,
        borderBottom: true,
        underline: false,
      },
      h3: {
        fontSize: 20,
        fontWeight: 600,
        color: "#15803d",
        spacingTop: 28,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 17,
        fontWeight: 600,
        color: "#16a34a",
        spacingTop: 24,
        spacingBottom: 6,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 15,
        fontWeight: 600,
        color: "#22c55e",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 13,
        fontWeight: 500,
        color: "#4ade80",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#14532d",
        h2: "#166534",
        h3: "#15803d",
        h4: "#16a34a",
        h5: "#22c55e",
        h6: "#4ade80",
      },
      bodyTextColor: "#1c2b1e",
      secondaryTextColor: "#4b6b52",
      linkColor: "#16a34a",
      visitedLinkColor: "#14532d",
      blockquoteBorderColor: "#22c55e",
      blockquoteBackgroundColor: "#f0fdf4",
      tableHeaderBackground: "#14532d",
      tableHeaderTextColor: "#f0fdf4",
      tableRowAlternateColor: "#f0fdf4",
      tableBorderColor: "#dcfce7",
      inlineCodeBackground: "#dcfce7",
      inlineCodeTextColor: "#15803d",
      pageBackgroundColor: "#f8fdf9",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "vitesse-light",
  },

  "rose-gold": {
    name: "rose-gold",
    displayName: "Rose Gold",
    fonts: {
      body: {
        family: "Nunito",
        size: 15,
        lineHeight: 1.75,
        letterSpacing: -0.01,
        weight: 400,
      },
      heading: {
        family: "Cormorant Garamond",
        size: 32,
        lineHeight: 1.2,
        letterSpacing: -0.03,
        weight: 700,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 13,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 700,
        color: "#881337",
        spacingTop: 16,
        spacingBottom: 14,
        borderBottom: false,
        underline: false,
      },
      h2: {
        fontSize: 26,
        fontWeight: 700,
        color: "#9f1239",
        spacingTop: 40,
        spacingBottom: 10,
        borderBottom: true,
        underline: false,
      },
      h3: {
        fontSize: 20,
        fontWeight: 600,
        color: "#be123c",
        spacingTop: 28,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 17,
        fontWeight: 600,
        color: "#e11d48",
        spacingTop: 24,
        spacingBottom: 6,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 15,
        fontWeight: 600,
        color: "#f43f5e",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 13,
        fontWeight: 500,
        color: "#fb7185",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#881337",
        h2: "#9f1239",
        h3: "#be123c",
        h4: "#e11d48",
        h5: "#f43f5e",
        h6: "#fb7185",
      },
      bodyTextColor: "#1f0a10",
      secondaryTextColor: "#9f7a84",
      linkColor: "#e11d48",
      visitedLinkColor: "#9f1239",
      blockquoteBorderColor: "#f43f5e",
      blockquoteBackgroundColor: "#fff1f2",
      tableHeaderBackground: "#881337",
      tableHeaderTextColor: "#fff1f2",
      tableRowAlternateColor: "#fff1f2",
      tableBorderColor: "#fee2e2",
      inlineCodeBackground: "#ffe4e6",
      inlineCodeTextColor: "#be123c",
      pageBackgroundColor: "#fffbfc",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "rose-pine",
  },

  "ivory-academic": {
    name: "ivory-academic",
    displayName: "Ivory Academic",
    fonts: {
      body: {
        family: "Libre Baskerville",
        size: 15,
        lineHeight: 1.75,
        letterSpacing: -0.01,
        weight: 400,
      },
      heading: {
        family: "Libre Baskerville",
        size: 32,
        lineHeight: 1.2,
        letterSpacing: -0.03,
        weight: 700,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 13,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 700,
        color: "#1b1b1b",
        spacingTop: 16,
        spacingBottom: 14,
        borderBottom: false,
        underline: false,
      },
      h2: {
        fontSize: 26,
        fontWeight: 700,
        color: "#2b2b2b",
        spacingTop: 40,
        spacingBottom: 10,
        borderBottom: true,
        underline: false,
      },
      h3: {
        fontSize: 20,
        fontWeight: 600,
        color: "#3b3b3b",
        spacingTop: 28,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 17,
        fontWeight: 600,
        color: "#4b4b4b",
        spacingTop: 24,
        spacingBottom: 6,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 15,
        fontWeight: 600,
        color: "#5b5b5b",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 13,
        fontWeight: 500,
        color: "#6b6b6b",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#1b1b1b",
        h2: "#2b2b2b",
        h3: "#3b3b3b",
        h4: "#4b4b4b",
        h5: "#5b5b5b",
        h6: "#6b6b6b",
      },
      bodyTextColor: "#2e2e2e",
      secondaryTextColor: "#7a7a7a",
      linkColor: "#2563eb",
      visitedLinkColor: "#1e40af",
      blockquoteBorderColor: "#2563eb",
      blockquoteBackgroundColor: "#f8fafc",
      tableHeaderBackground: "#2e2e2e",
      tableHeaderTextColor: "#ffffff",
      tableRowAlternateColor: "#fafafa",
      tableBorderColor: "#e5e7eb",
      inlineCodeBackground: "#f1f5f9",
      inlineCodeTextColor: "#1e40af",
      pageBackgroundColor: "#fffdf7",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "github-light",
  },

  "soft-sky": {
    name: "soft-sky",
    displayName: "Soft Sky",
    fonts: {
      body: {
        family: "Inter",
        size: 15,
        lineHeight: 1.75,
        letterSpacing: -0.01,
        weight: 400,
      },
      heading: {
        family: "Inter",
        size: 32,
        lineHeight: 1.2,
        letterSpacing: -0.03,
        weight: 800,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 13,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 800,
        color: "#0c4a6e",
        spacingTop: 16,
        spacingBottom: 14,
        borderBottom: false,
        underline: false,
      },
      h2: {
        fontSize: 26,
        fontWeight: 700,
        color: "#075985",
        spacingTop: 40,
        spacingBottom: 10,
        borderBottom: true,
        underline: false,
      },
      h3: {
        fontSize: 20,
        fontWeight: 600,
        color: "#0284c7",
        spacingTop: 28,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 17,
        fontWeight: 600,
        color: "#0ea5e9",
        spacingTop: 24,
        spacingBottom: 6,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 15,
        fontWeight: 600,
        color: "#38bdf8",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 14,
        fontWeight: 500,
        color: "#7dd3fc",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#0c4a6e",
        h2: "#075985",
        h3: "#0284c7",
        h4: "#0ea5e9",
        h5: "#38bdf8",
        h6: "#7dd3fc",
      },
      bodyTextColor: "#0f172a",
      secondaryTextColor: "#64748b",
      linkColor: "#0284c7",
      visitedLinkColor: "#075985",
      blockquoteBorderColor: "#38bdf8",
      blockquoteBackgroundColor: "#f0f9ff",
      tableHeaderBackground: "#0c4a6e",
      tableHeaderTextColor: "#ffffff",
      tableRowAlternateColor: "#f8fafc",
      tableBorderColor: "#e2e8f0",
      inlineCodeBackground: "#e0f2fe",
      inlineCodeTextColor: "#0369a1",
      pageBackgroundColor: "#f9fcff",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "github-light",
  },

  "warm-paper": {
    name: "warm-paper",
    displayName: "Warm Paper",
    fonts: {
      body: {
        family: "Crimson Pro",
        size: 17,
        lineHeight: 1.75,
        letterSpacing: -0.01,
        weight: 400,
      },
      heading: {
        family: "Crimson Pro",
        size: 36,
        lineHeight: 1.2,
        letterSpacing: -0.03,
        weight: 800,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 13,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 42,
        fontWeight: 900,
        color: "#7c2d12",
        spacingTop: 16,
        spacingBottom: 14,
        borderBottom: false,
        underline: false,
      },
      h2: {
        fontSize: 32,
        fontWeight: 700,
        color: "#9a3412",
        spacingTop: 40,
        spacingBottom: 10,
        borderBottom: true,
        underline: false,
      },
      h3: {
        fontSize: 24,
        fontWeight: 600,
        color: "#c2410c",
        spacingTop: 28,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 20,
        fontWeight: 600,
        color: "#ea580c",
        spacingTop: 24,
        spacingBottom: 6,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 18,
        fontWeight: 600,
        color: "#fb923c",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 16,
        fontWeight: 500,
        color: "#fdba74",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#7c2d12",
        h2: "#9a3412",
        h3: "#c2410c",
        h4: "#ea580c",
        h5: "#fb923c",
        h6: "#fdba74",
      },
      bodyTextColor: "#3f2a1d",
      secondaryTextColor: "#a16207",
      linkColor: "#ea580c",
      visitedLinkColor: "#9a3412",
      blockquoteBorderColor: "#fb923c",
      blockquoteBackgroundColor: "#fff7ed",
      tableHeaderBackground: "#7c2d12",
      tableHeaderTextColor: "#fff7ed",
      tableRowAlternateColor: "#fff7ed",
      tableBorderColor: "#fed7aa",
      inlineCodeBackground: "#ffedd5",
      inlineCodeTextColor: "#c2410c",
      pageBackgroundColor: "#fffaf3",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "github-light",
  },

  "pastel-notes": {
    name: "pastel-notes",
    displayName: "Pastel Notes",
    fonts: {
      body: {
        family: "Nunito",
        size: 15,
        lineHeight: 1.75,
        letterSpacing: -0.01,
        weight: 400,
      },
      heading: {
        family: "Nunito",
        size: 32,
        lineHeight: 1.2,
        letterSpacing: -0.03,
        weight: 800,
      },
      monospace: {
        family: "JetBrains Mono",
        size: 13,
        lineHeight: 1.6,
        letterSpacing: 0,
        weight: 400,
      },
    },
    headings: {
      h1: {
        fontSize: 36,
        fontWeight: 800,
        color: "#6d28d9",
        spacingTop: 16,
        spacingBottom: 14,
        borderBottom: false,
        underline: false,
      },
      h2: {
        fontSize: 26,
        fontWeight: 700,
        color: "#7c3aed",
        spacingTop: 40,
        spacingBottom: 10,
        borderBottom: true,
        underline: false,
      },
      h3: {
        fontSize: 20,
        fontWeight: 600,
        color: "#8b5cf6",
        spacingTop: 28,
        spacingBottom: 8,
        borderBottom: false,
        underline: false,
      },
      h4: {
        fontSize: 17,
        fontWeight: 600,
        color: "#a78bfa",
        spacingTop: 24,
        spacingBottom: 6,
        borderBottom: false,
        underline: false,
      },
      h5: {
        fontSize: 15,
        fontWeight: 600,
        color: "#c4b5fd",
        spacingTop: 20,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
      h6: {
        fontSize: 13,
        fontWeight: 500,
        color: "#ddd6fe",
        spacingTop: 16,
        spacingBottom: 4,
        borderBottom: false,
        underline: false,
      },
    },
    colors: {
      headingColors: {
        h1: "#6d28d9",
        h2: "#7c3aed",
        h3: "#8b5cf6",
        h4: "#a78bfa",
        h5: "#c4b5fd",
        h6: "#ddd6fe",
      },
      bodyTextColor: "#1f2937",
      secondaryTextColor: "#6b7280",
      linkColor: "#7c3aed",
      visitedLinkColor: "#6d28d9",
      blockquoteBorderColor: "#a78bfa",
      blockquoteBackgroundColor: "#f5f3ff",
      tableHeaderBackground: "#6d28d9",
      tableHeaderTextColor: "#ffffff",
      tableRowAlternateColor: "#faf5ff",
      tableBorderColor: "#e9d5ff",
      inlineCodeBackground: "#ede9fe",
      inlineCodeTextColor: "#6d28d9",
      pageBackgroundColor: "#fcfbff",
    },
    bodyText: {
      paragraphSpacing: 16,
      textAlignment: "left",
      firstLineIndent: false,
    },
    codeTheme: "github-light",
  },
}
